var chai = require('chai');
var context = global || this;
context._ = require("underscore");
context.expect = chai.expect;
context.should = chai.should();
context.uw = require("../lib/underwear-util");
chai.use(require('chai-fuzzy'));
require("../lib/array");
require("../lib/object");
require("../lib/string");
require("../lib/utilities");
